### ISSUE TITLE
doesnt render properly 

### ISSUE THREAD

**Issue by barisusakli** [NodeBB/nodebb-plugin-iframely#42]
https://community.nodebb.org/topic/10963/test-iframely/6

**Comment by iparamonau** [comment]
Hey Baris, this fix causes issues. There will be no embedded player now, say, for YouTube. Basically, it seems because `image` is always set now,  that with `!image` condition [here](https://github.com/NodeBB-Community/nodebb-plugin-iframely/commit/aa20e78678726722cd6f7d66131dd136ac63c047#diff-23d0409eda55ae4e1330ef5acbab63f8R166) you have disabled all HTML.

Can you recall what was the issue that you tried to fix so that we do not override it?

cc @nleush

**Comment by barisusakli** [comment]
Hmm if I remember correctly without this change the links in the topic were rendered as just text and a link.

**Comment by iparamonau** [comment]
I think we reconstructed the commits history now. 

- It looks you guys added the post  sanitizers in the core first.
- It disabled a bunch of Iframely embeds (because we have our embed.js script in some media).
- But also it disabled embeds from Twitter, Instagram and the like.
- So you wanted to return the unfurling of such URLs with thumbnail image and title, but accidentally covered all URLs with any HTML codes - including iFrames such as YouTube, for example.

We are putting a proper fix together as we had a support request for it. 
Let us know if you guys had something different in mind. Basically, we're going to return all iFrames html and also will load Iframely embed.js script when needed.

**Comment by barisusakli** [comment]
That sounds good, cc @julianlam

Let us know when a new version is published so I can update it on our community and test as well.
